<a href="https://colab.research.google.com/github/ardioputra/orange-grapefruit/blob/main/practice_santuy_sgd_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('citrus.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [4]:
df.head(1000)

name  diameter  weight  red  green  blue
0    orange      2.96   86.76  172     85     2
1    orange      3.91   88.05  166     78     3
2    orange      4.42   95.17  156     81     2
3    orange      4.47   95.60  163     81     4
4    orange      4.48   95.76  161     72     9
..      ...       ...     ...  ...    ...   ...
995  orange      7.43  137.10  158     78     3
996  orange      7.44  137.12  164     97     2
997  orange      7.44  137.18  140     88     2
998  orange      7.44  137.23  148     85     2
999  orange      7.44  137.24  166     83     7

[1000 rows x 6 columns]

In [5]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [6]:
dataset = df.values
dataset

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

In [7]:
X = dataset[:,1:6]
y = dataset[:,0]

In [8]:
X

array([[2.96, 86.76, 172, 85, 2],
       [3.91, 88.05, 166, 78, 3],
       [4.42, 95.17, 156, 81, 2],
       ...,
       [15.59, 256.5, 168, 82, 20],
       [15.92, 260.14, 142, 72, 11],
       [16.45, 261.51, 152, 74, 2]], dtype=object)

In [9]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

In [11]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [15]:
Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [16]:
from keras.models import Sequential
from keras.layers import Dense

In [17]:
model = Sequential([
                    Dense(32, activation='relu', input_shape=(5,)),
                    Dense(32, activation='relu'),
                    Dense(1, activation='sigmoid')
])

In [18]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [19]:
model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 1s 2ms/step - loss: 0.6623 - accuracy: 0.7441
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.6012 - accuracy: 0.9010
Epoch 3/100
219/219 [==============================] - 0s 2ms/step - loss: 0.5247 - accuracy: 0.9176
Epoch 4/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.9226
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3406 - accuracy: 0.9231
Epoch 6/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2779 - accuracy: 0.9254
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2398 - accuracy: 0.9271
Epoch 8/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2179 - accuracy: 0.9269
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.2048 - accuracy: 0.9264
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.1965 - accura

In [20]:
model.evaluate(X_test, Y_test)

94/94 [==============================] - 0s 1ms/step - loss: 0.1705 - accuracy: 0.9293


[0.17053179442882538, 0.9293333292007446]